### ISSUE TITLE
Code Tooling: Linting, Formatting, Type Annotations, etc

### ISSUE THREAD

**Issue by DM-Berger** [Ashcoding1/soccer_analytics#2]
We need to decide on some basic coding tools and configurations to ensure minimal code quality, and reduce pointless conflicts in diffs / merges. IMO, the most important things here are:

1. linting
2. formatting
3. import sorting
4. type annotations

# Python

I have a default setup for Python, which we could start with. It uses

- **black** for formatting, with a line-length of either 100, 110, or 120
- **isort** for import sorting
- **flake8** for linting with only some rules disabled
- **mypy** with fairly-strict rules overall

The configs would start like below:

`.flake8`
```ini
[flake8]
# ignored rules, see https://lintlyci.github.io/Flake8Rules/
# E302: Expected 2 blank lines, found 0
# E731: Do not assign a lambda expression, use a def
# W503: Line break occurred before a binary operator
ignore = E302,E731,W503
max-line-length = 100
```
`mypy.ini`
```ini
[mypy]
python_version = 3.10
ignore_missing_imports = True
follow_imports = normal
warn_return_any = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = False
warn_no_return = True
warn_unreachable = True
allow_redefinition = True
```
`pyproject.toml`
```toml
[tool.black]
line-length = 100

[tool.isort]
profile = 'black'
skip_gitignore = false
line_length = 100
atomic = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'LOCALFOLDER', 'FIRSTPARTY']
known_local_folder = ['src', 'test', 'tests', 'app']

```

# TS / JS / TSX

It has been a while since I have done this. If we only use TS / TSX (no JS - which I recommend), then we will need to configure [TS ESLint](https://typescript-eslint.io/), [Prettier](https://prettier.io/) for code formatting, Import sorting via [VSCode extension](https://marketplace.visualstudio.com/items?itemName=mike-co.import-sorter&ssr=false#review-details) which uses ESLint import sorting rules.

TS can still [find type errors in JS](https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html) so we should also make sure we pass these checks if we do write any plain JS files. 

But because it has been so long since I have worked with these, we probably want to start with some default rules, and just modify as needed. But we should definitely setup some basic configs and commit them ASAP.
